#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/commons

function clean_autotools_generated_files() {
rm -rf \
aclocal.m4 \
autom4te.cache \
config.log \
config.status \
configure \
depcomp \
install-sh \
Makefile \
Makefile.in \
missing \
autoscan.log \
config.guess \
config.sub
}

echo $1
cd $1
make clean
clean_autotools_generated_files
