#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/commons
CLEAN=$SCRIPTPATH/clean_generated_files

POCO_SRC=deps/src/poco/
DEPS_USR=deps/usr/

root
$CLEAN $DEPS_USR all
$CLEAN $POCO_SRC poco_root
find $POCO_SRC -type d -exec $CLEAN {} poco \;
