#!/bin/bash

# The absolute path to this script
SCRIPT=$(readlink -f $0)
# The absolute path to the scripts directory
SCRIPTPATH=$(dirname $SCRIPT)
ROOT=$SCRIPTPATH/..

function root() {
  cd $SCRIPTPATH/../
}
